# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'


steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    configuration: 'Release'
    publishWebProjects: true
    zipAfterPublish: true
    projects: '**/*.csproj'
    arguments: '--configuration Release -o output'
#- script: |
#    npm install
#    npm run build
#  workingDirectory: BingeBuddyNg/BingeBuddyNg.Spa
#  displayName: 'Build Frontend'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/BingeBuddyNg/output'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
#- task: CopyFiles@2
#  inputs:
#    SourceFolder: '$(build.sourcesdirectory)/BingeBuddyNg/BingeBuddyNg.Spa/dist/'
#    Contents: '**'
#    TargetFolder: '$(Build.ArtifactStagingDirectory)/Spa'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'