# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'


steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish Api'
  inputs:
    command: 'publish'
    configuration: 'Release'
    publishWebProjects: true
    zipAfterPublish: true
    modifyOutputPath: true
    projects: 'BingeBuddyNg/BingeBuddyNg.Api/BingeBuddyNg.Api.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/api'
- task: DotNetCoreCLI@2
  displayName: 'Publish Functions'
  inputs:
    command: 'publish'
    configuration: 'Release'
    publishWebProjects: true
    zipAfterPublish: true
    projects: 'BingeBuddyNg/BingeBuddyNg.Functions/BingeBuddyNg.Functions.csproj'
    modifyOutputPath: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/functions'
- script: |
    npm install
    npm run build
  workingDirectory: BingeBuddyNg/BingeBuddyNg.Spa
  displayName: 'Build Frontend'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'