# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'


steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    configuration: 'Release'
    publishWebProjects: true
    projects: '**/*.csproj'
- script: |
    npm install
    npm run build
  workingDirectory: BingeBuddyNg/BingeBuddyNg.Spa
  displayName: 'Build Frontend'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/BingeBuddyNg/BingeBuddyNg.Api/bin/Release/netcoreapp3.1/publish/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Api'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/BingeBuddyNg/BingeBuddyNg.Functions/bin/Release/netcoreapp3.1/publish/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Functions'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'