# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish BingeBuddyNg/BingeBuddyNg.Api/BingeBuddyNg.Api.csproj --configuration $(buildConfiguration)
  displayName: 'Publish Api'
- script: dotnet publish BingeBuddyNg/BingeBuddyNg.Functions/BingeBuddyNg.Functions.csproj --configuration $(buildConfiguration)
  displayName: 'Publish Functions'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  workingDirectory: BingeBuddyNg/BingeBuddyNg.Spa
  displayName: 'npm install and build'
  